project_id = "yobppwbtiqzsplifrtoz"

[functions.send-contact-notification]
verify_jwt = false

[functions.import-blog-images]
verify_jwt = false

[functions.generate-blog-images]
verify_jwt = false

[functions.mapbox-public-token]
verify_jwt = false

[functions.send-container-offer]
verify_jwt = false

[functions.calculate-duty]
verify_jwt = false
